library(fs)
library(purrr)
library(here)

dirs <- c(here("data"), here("figs"))
dirs <- keep(dirs, dir_exists())
#
# make-clean deletes all the downstream/intermediate products generated by your scripts.
# make-all generates everything from scratch
#
# instead of source source source, could use pacakge from gabor(ta), callr::r
#
#   runs in independent r sessions, whereas source source source runs them one after another
